"""
Sector group mappings used for building benchmark series.
"""

SECTOR_GROUPS = {
    "Commercial Banks": {
        "ADBL",
        "CZBIL",
        "EBL",
        "GBIME",
        "HBL",
        "KBL",
        "LSL",
        "MBL",
        "NABIL",
        "NBL",
        "NICA",
        "NIMB",
        "NMB",
        "PCBL",
        "PRVU",
        "RBB",
        "SANIMA",
        "SBI",
        "SBL",
        "SCB",
    },
    "Development Banks": {
        "CORBL",
        "EDBL",
        "GBBL",
        "GRDBL",
        "JBBL",
        "KRBL",
        "KSBBL",
        "LBBL",
        "MDB",
        "MLBL",
        "MNBBL",
        "NABBC",
        "SADBL",
        "SAPDBL",
        "SHINE",
        "SINDU",
    },
    "Finance": {
        "BFC",
        "CFCL",
        "GFCL",
        "GMFIL",
        "GUFL",
        "ICFC",
        "JFL",
        "MFIL",
        "MPFL",
        "NFS",
        "PFL",
        "PROFL",
        "RLFL",
        "SFCL",
        "SIFC",
    },
    "Hydropower": {
        "AHPC",
        "AKJCL",
        "AKPL",
        "API",
        "BARUN",
        "BHL",
        "BNHC",
        "BPCL",
        "CHCL",
        "CHL",
        "DHPL",
        "DORDI",
        "GHL",
        "GLH",
        "GVL",
        "HDHPC",
        "HPPL",
        "HURJA",
        "JOSHI",
        "KKHC",
        "KPCL",
        "LEC",
        "MBJC",
        "MHNL",
        "MKHC",
        "MKJC",
        "NGPL",
        "NHPC",
        "NYADI",
        "PMHPL",
        "PPCL",
        "RADHI",
        "RFPL",
        "RURU",
        "SAHAS",
        "SHEL",
        "SHPC",
        "SIKLES",
        "SJCL",
        "SPC",
        "SPDL",
        "SPL",
        "SSHL",
        "TPC",
        "UHEWA",
        "UMHL",
        "UMRH",
        "UNHPL",
        "UPCL",
        "UPPER",
        "USHEC",
    },
    "Life Insurance": {
        "ALICL",
        "CLI",
        "HLI",
        "IMEL",
        "LICN",
        "NATRIS",
        "NLIC",
        "PMLI",
        "RNLI",
        "SJLIC",
        "SNLI",
        "SRLI",
    },
    "Non-Life Insurance": {
        "HGI",
        "IGIPR",
        "NECO",
        "NICL",
        "NIL",
        "NLG",
        "PRIN",
        "RBCL",
        "SALICO",
        "SGIC",
        "SIC",
        "SICL",
        "UAIL",
    },
    "Microfinance": {
        "ALBSL",
        "CBBL",
        "DDBL",
        "FMDBL",
        "FOWAD",
        "GBLBS",
        "GILB",
        "JBLB",
        "KMCDB",
        "LLBS",
        "MLBBL",
        "MLBS",
        "MLBSL",
        "MNBBL",
        "MERO",
        "MERO",
        "MSLB",
        "NICLBSL",
        "NUBL",
        "NESDO",
        "RSDC",
        "SKBBL",
        "SMB",
        "SMATA",
        "SMFDB",
        "SWBBL",
        "USLB",
        "VLBS",
        "WNLB",
    },
    "Hotels & Tourism": {"CGH", "CITY", "KDL", "OHL", "SHL", "TRH", "BANDIPUR"},
    "Manufacturing & Processing": {"BNT", "GCIL", "HDL", "NLO", "SARBTM", "SHIVM", "SONA", "UNL"},
    "Investment": {"CHDC", "CIT", "HATHY", "HIDCL", "NIFRA", "NRN"},
    "Others": {"HRL", "NRIC", "NTC"},
    "Trading": {"BBC", "STC"},
}

SECTOR_LOOKUP = {
    symbol: sector for sector, members in SECTOR_GROUPS.items() for symbol in members
}

__all__ = ["SECTOR_GROUPS", "SECTOR_LOOKUP"]
